# A example scrape configuration for running Prometheus with Ovhcloud.
scrape_configs:
  - job_name: 'prometheus'
    ovhcloud_sd_configs:
      - application_key: XXX
        application_secret: XXX
        consumer_key: XXX
        endpoint: ovh-eu
